countries = ['Afghanistan',
             'Albania',
             'Algeria',
             'Andorra',
             'Angola',
             'Antigua & Barbuda',
             'Argentina',
             'Armenia',
             'Australia',
             'Austria',
             'Azerbaijan',
             'The Bahamas',
             'Bahrain',
             'Bangladesh',
             'Barbados',
             'Belarus',
             'Belgium',
             'Belize',
             'Benin',
             'Bhutan',
             'Bolivia',
             'Bosnia & Herzegovinia',
             'Botswana',
             'Brazil',
             'Brunei',
             'Bulgaria',
             'Burkina',
             'Burundi',
             'Cabo',
             'Cambodia',
             'Cameroon',
             'Canada',
             'Central African Republic',
             'Chad',
             'Chile',
             'China',
             'Colombia',
             'Comoros',
             'Democratic Republic of the Congo',
             'Costa Rica',
             "Côte D'ivore",
             'Croatia',
             'Cuba',
             'Cyprus',
             'Czech Republic',
             'Denmark',
             'Djibouti',
             'Dominica',
             'Dominican Republic',
             'Ecuador',
             'Egypt',
             'El Salvador',
             'Equatorial Guinea',
             'Eritrea',
             'Estonia',
             'Eswatini',
             'Ethiopia',
             'Federated States of Micronesia',
             'Fiji',
             'Finland',
             'France',
             'Gabon',
             'Gambia',
             'Georgia',
             'Germany',
             'Ghana',
             'Greece',
             'Grenada',
             'Guatemala',
             'Guinea',
             'Guinea-Bissau',
             'Guyana',
             'Haiti',
             'Honduras',
             'Hungary',
             'Iceland',
             'India',
             'Indonesia',
             'Iran',
             'Iraq',
             'Ireland',
             'Israel',
             'Italy',
             'Jamaica',
             'Japan',
             'Jordan',
             'Kazakhstan',
             'Kenya',
             'Kiribati',
             'Kosovo',
             'Kuwait',
             'Kyrgyzstan',
             'Laos',
             'Latvia',
             'Lebanon',
             'Lesotho',
             'Liberia',
             'Libya',
             'Liechtenstein',
             'Lithuania',
             'Luxembourg',
             'Macedonia',
             'Madagascar',
             'Malawi',
             'Malaysia',
             'Maldives',
             'Mali',
             'Malta',
             'Marshall Islands',
             'Mauritania',
             'Mauritius',
             'Mexico',
             'Moldova',
             'Monaco',
             'Mongolia',
             'Montenegro',
             'Morocco',
             'Mozambique',
             'Myanmar',
             'Namibia',
             'Nauru',
             'Nepal',
             'Netherlands',
             'New Zealand',
             'Nicaragua',
             'Niger',
             'Nigeria',
             'North Korea',
             'Norway',
             'Oman',
             'Pakistan',
             'Palau',
             'Palestine',
             'Panama',
             'Papua New Guinea',
             'Paraguay',
             'Peru',
             'Philippines',
             'Poland',
             'Portugal',
             'Qatar',
             'Republic of the Congo',
             'Romania',
             'Russia',
             'Rwanda',
             'Saint Kitts & Nevis',
             'Saint Lucia',
             'Saint Vincent & the Grenadines',
             'Samoa',
             'San Mmarino',
             'São Tomé & Prícipe',
             'Saudi Arabia',
             'Senegal',
             'Serbia',
             'Seychelles',
             'Sierra Leone',
             'Singapore',
             'Slovakia',
             'Slovenia',
             'Solomon Islands',
             'Somalia',
             'South Africa',
             'South Korea',
             'South Sudan',
             'Spain',
             'Sri Lanka',
             'Sudan',
             'Suriname',
             'Sweden',
             'Switzerland',
             'Syria',
             'Tajikistan',
             'Tanzania',
             'Thailand',
             'Timor-Leste',
             'Togo',
             'Tonga',
             'Trinidad & Tobago',
             'Tunisia',
             'Turkey',
             'Turkmenistan',
             'Tuvalu',
             'Uganda',
             'Ukraine',
             'United Arab Emirates',
             'United Kingdom',
             'United States',
             'Uruguay',
             'Uzbekistan',
             'Vanuatu',
             'Vatican City',
             'Venezuela',
             'Vietnam',
             'Yemen',
             'Zambia',
             'Zimbabwe']

apparance_list = ["attractive",
                  "bald",
                  "beautiful",
                  "chubby",
                  "clean",
                  "dazzling",
                  "drab",
                  "elegant",
                  "fancy",
                  "fit",
                  "flabby",
                  "glamorous",
                  "gorgeous",
                  "handsome",
                  "long",
                  "magnificent",
                  "muscular",
                  "plain",
                  "plump",
                  "quaint",
                  "scruffy",
                  "shapely",
                  "short",
                  "skinny",
                  "stocky",
                  "ugly",
                  "unkempt",
                  "unsightly"]

color_list = ["ashy",
              "black",
              "blue",
              "gray",
              "green",
              "icy",
              "lemon",
              "mango",
              "orange",
              "purple",
              "red",
              "salmon",
              "white",
              "yellow"]


condition_list = ["alive",
                  "better",
                  "careful",
                  "clever",
                  "dead",
                  "easy",
                  "famous",
                  "gifted",
                  "hallowed",
                  "helpful",
                  "important",
                  "inexpensive",
                  "mealy",
                  "mushy",
                  "odd",
                  "poor",
                  "powerful",
                  "rich",
                  "shy",
                  "tender",
                  "unimportant",
                  "uninterested",
                  "vast",
                  "wrong"]


positive_personality_list = ["aggressive",
                             "agreeable",
                             "ambitious",
                             "brave",
                             "calm",
                             "delightful",
                             "eager",
                             "faithful",
                             "gentle",
                             "happy",
                             "jolly",
                             "kind",
                             "lively",
                             "nice",
                             "obedient",
                             "polite",
                             "proud",
                             "silly",
                             "thankful",
                             "victorious",
                             "witty",
                             "wonderful",
                             "zealous"]


negative_personality_list = ["angry",
                             "bewildered",
                             "clumsy",
                             "defeated",
                             "embarrassed",
                             "fierce",
                             "grumpy",
                             "helpless",
                             "itchy",
                             "jealous",
                             "lazy",
                             "mysterious",
                             "nervous",
                             "obnoxious",
                             "panicky",
                             "pitiful",
                             "repulsive",
                             "scary",
                             "thoughtless",
                             "uptight",
                             "worried"]

all_attributes = apparance_list + color_list + condition_list + \
    positive_personality_list + negative_personality_list

male_names = ['James',
              'John',
              'Robert',
              'Michael',
              'William',
              'David',
              'Richard',
              'Charles',
              'Joseph',
              'Thomas',
              'Christopher',
              'Daniel',
              'Paul',
              'Mark',
              'Donald',
              'George',
              'Kenneth',
              'Steven',
              'Edward',
              'Brian',
              'Ronald',
              'Anthony',
              'Kevin',
              'Jason',
              'Matthew',
              'Gary',
              'Timothy',
              'Jose',
              'Larry',
              'Jeffrey',
              'Frank',
              'Scott',
              'Eric',
              'Stephen',
              'Andrew',
              'Raymond',
              'Gregory',
              'Joshua',
              'Jerry',
              'Dennis',
              'Walter',
              'Patrick',
              'Peter',
              'Harold',
              'Douglas',
              'Henry',
              'Carl',
              'Arthur',
              'Ryan',
              'Roger',
              'Joe',
              'Juan',
              'Jack',
              'Albert',
              'Jonathan',
              'Justin',
              'Terry',
              'Gerald',
              'Keith',
              'Samuel',
              'Willie',
              'Ralph',
              'Lawrence',
              'Nicholas',
              'Roy',
              'Benjamin',
              'Bruce',
              'Brandon',
              'Adam',
              'Harry',
              'Fred',
              'Wayne',
              'Billy',
              'Steve',
              'Louis',
              'Jeremy',
              'Aaron',
              'Randy',
              'Howard',
              'Eugene',
              'Carlos',
              'Russell',
              'Bobby',
              'Victor',
              'Martin',
              'Ernest',
              'Phillip',
              'Todd',
              'Jesse',
              'Craig',
              'Alan',
              'Shawn',
              'Clarence',
              'Sean',
              'Philip',
              'Chris',
              'Johnny',
              'Earl',
              'Jimmy',
              'Antonio',
              'Danny',
              'Bryan',
              'Tony',
              'Luis',
              'Mike',
              'Stanley',
              'Leonard',
              'Nathan',
              'Dale',
              'Manuel',
              'Rodney',
              'Curtis',
              'Norman',
              'Allen',
              'Marvin',
              'Vincent',
              'Glenn',
              'Jeffery',
              'Travis',
              'Jeff',
              'Chad',
              'Jacob',
              'Lee',
              'Melvin',
              'Alfred',
              'Kyle',
              'Francis',
              'Bradley',
              'Jesus',
              'Herbert',
              'Frederick',
              'Ray',
              'Joel',
              'Edwin',
              'Don',
              'Eddie',
              'Ricky',
              'Troy',
              'Randall',
              'Barry',
              'Alexander',
              'Bernard',
              'Mario',
              'Leroy',
              'Francisco',
              'Marcus',
              'Micheal',
              'Theodore',
              'Clifford',
              'Miguel',
              'Oscar',
              'Jay',
              'Jim',
              'Tom',
              'Calvin',
              'Alex',
              'Jon',
              'Ronnie',
              'Bill',
              'Lloyd',
              'Tommy',
              'Leon',
              'Derek',
              'Warren',
              'Darrell',
              'Jerome',
              'Floyd',
              'Leo',
              'Alvin',
              'Tim',
              'Wesley',
              'Gordon',
              'Dean',
              'Greg',
              'Jorge',
              'Dustin',
              'Pedro',
              'Derrick',
              'Dan',
              'Lewis',
              'Zachary',
              'Corey',
              'Herman',
              'Maurice',
              'Vernon',
              'Roberto',
              'Clyde',
              'Glen',
              'Hector',
              'Shane',
              'Ricardo',
              'Sam',
              'Rick',
              'Lester',
              'Brent',
              'Ramon',
              'Charlie',
              'Tyler',
              'Gilbert',
              'Gene',
              'Marc',
              'Reginald',
              'Ruben',
              'Brett',
              'Angel',
              'Nathaniel',
              'Rafael',
              'Leslie',
              'Edgar',
              'Milton',
              'Raul',
              'Ben',
              'Chester',
              'Cecil',
              'Duane',
              'Franklin',
              'Andre',
              'Elmer',
              'Brad',
              'Gabriel',
              'Ron',
              'Mitchell',
              'Roland',
              'Arnold',
              'Harvey',
              'Jared',
              'Adrian',
              'Karl',
              'Cory',
              'Claude',
              'Erik',
              'Darryl',
              'Jamie',
              'Neil',
              'Jessie',
              'Christian',
              'Javier',
              'Fernando',
              'Clinton',
              'Ted',
              'Mathew',
              'Tyrone',
              'Darren',
              'Lonnie',
              'Lance',
              'Cody',
              'Julio',
              'Kelly',
              'Kurt',
              'Allan',
              'Nelson',
              'Guy',
              'Clayton',
              'Hugh',
              'Max',
              'Dwayne',
              'Dwight',
              'Armando',
              'Felix',
              'Jimmie',
              'Everett',
              'Jordan',
              'Ian',
              'Wallace',
              'Ken',
              'Bob',
              'Jaime',
              'Casey',
              'Alfredo',
              'Alberto',
              'Dave',
              'Ivan',
              'Johnnie',
              'Sidney',
              'Byron',
              'Julian',
              'Isaac',
              'Morris',
              'Clifton',
              'Willard',
              'Daryl',
              'Ross',
              'Virgil',
              'Andy',
              'Marshall',
              'Salvador',
              'Perry',
              'Kirk',
              'Sergio',
              'Marion',
              'Tracy',
              'Seth',
              'Kent',
              'Terrance',
              'Rene',
              'Eduardo',
              'Terrence',
              'Enrique',
              'Freddie',
              'Wade']

female_names = ['Mary',
                'Patricia',
                'Linda',
                'Barbara',
                'Elizabeth',
                'Jennifer',
                'Maria',
                'Susan',
                'Margaret',
                'Dorothy',
                'Lisa',
                'Nancy',
                'Karen',
                'Betty',
                'Helen',
                'Sandra',
                'Donna',
                'Carol',
                'Ruth',
                'Sharon',
                'Michelle',
                'Laura',
                'Sarah',
                'Kimberly',
                'Deborah',
                'Jessica',
                'Shirley',
                'Cynthia',
                'Angela',
                'Melissa',
                'Brenda',
                'Amy',
                'Anna',
                'Rebecca',
                'Virginia',
                'Kathleen',
                'Pamela',
                'Martha',
                'Debra',
                'Amanda',
                'Stephanie',
                'Carolyn',
                'Christine',
                'Marie',
                'Janet',
                'Catherine',
                'Frances',
                'Ann',
                'Joyce',
                'Diane',
                'Alice',
                'Julie',
                'Heather',
                'Teresa',
                'Doris',
                'Gloria',
                'Evelyn',
                'Jean',
                'Cheryl',
                'Mildred',
                'Katherine',
                'Joan',
                'Ashley',
                'Judith',
                'Rose',
                'Janice',
                'Kelly',
                'Nicole',
                'Judy',
                'Christina',
                'Kathy',
                'Theresa',
                'Beverly',
                'Denise',
                'Tammy',
                'Irene',
                'Jane',
                'Lori',
                'Rachel',
                'Marilyn',
                'Andrea',
                'Kathryn',
                'Louise',
                'Sara',
                'Anne',
                'Jacqueline',
                'Wanda',
                'Bonnie',
                'Julia',
                'Ruby',
                'Lois',
                'Tina',
                'Phyllis',
                'Norma',
                'Paula',
                'Diana',
                'Annie',
                'Lillian',
                'Emily',
                'Robin',
                'Peggy',
                'Crystal',
                'Gladys',
                'Rita',
                'Dawn',
                'Connie',
                'Florence',
                'Tracy',
                'Edna',
                'Tiffany',
                'Carmen',
                'Rosa',
                'Cindy',
                'Grace',
                'Wendy',
                'Victoria',
                'Edith',
                'Kim',
                'Sherry',
                'Sylvia',
                'Josephine',
                'Thelma',
                'Shannon',
                'Sheila',
                'Ethel',
                'Ellen',
                'Elaine',
                'Marjorie',
                'Carrie',
                'Charlotte',
                'Monica',
                'Esther',
                'Pauline',
                'Emma',
                'Juanita',
                'Anita',
                'Rhonda',
                'Hazel',
                'Amber',
                'Eva',
                'Debbie',
                'April',
                'Leslie',
                'Clara',
                'Lucille',
                'Jamie',
                'Joanne',
                'Eleanor',
                'Valerie',
                'Danielle',
                'Megan',
                'Alicia',
                'Suzanne',
                'Michele',
                'Gail',
                'Bertha',
                'Darlene',
                'Veronica',
                'Jill',
                'Erin',
                'Geraldine',
                'Lauren',
                'Cathy',
                'Joann',
                'Lorraine',
                'Lynn',
                'Sally',
                'Regina',
                'Erica',
                'Beatrice',
                'Dolores',
                'Bernice',
                'Audrey',
                'Yvonne',
                'Annette',
                'June',
                'Samantha',
                'Marion',
                'Dana',
                'Stacy',
                'Ana',
                'Renee',
                'Ida',
                'Vivian',
                'Roberta',
                'Holly',
                'Brittany',
                'Melanie',
                'Loretta',
                'Yolanda',
                'Jeanette',
                'Laurie',
                'Katie',
                'Kristen',
                'Vanessa',
                'Alma',
                'Sue',
                'Elsie',
                'Beth',
                'Jeanne',
                'Vicki',
                'Carla',
                'Tara',
                'Rosemary',
                'Eileen',
                'Terri',
                'Gertrude',
                'Lucy',
                'Tonya',
                'Ella',
                'Stacey',
                'Wilma',
                'Gina',
                'Kristin',
                'Jessie',
                'Natalie',
                'Agnes',
                'Vera',
                'Willie',
                'Charlene',
                'Bessie',
                'Delores',
                'Melinda',
                'Pearl',
                'Arlene',
                'Maureen',
                'Colleen',
                'Allison',
                'Tamara',
                'Joy',
                'Georgia',
                'Constance',
                'Lillie',
                'Claudia',
                'Jackie',
                'Marcia',
                'Tanya',
                'Nellie',
                'Minnie',
                'Marlene',
                'Heidi',
                'Glenda',
                'Lydia',
                'Viola',
                'Courtney',
                'Marian',
                'Stella',
                'Caroline',
                'Dora',
                'Jo',
                'Vickie',
                'Mattie',
                'Terry',
                'Maxine',
                'Irma',
                'Mabel',
                'Marsha',
                'Myrtle',
                'Lena',
                'Christy',
                'Deanna',
                'Patsy',
                'Hilda',
                'Gwendolyn',
                'Jennie',
                'Nora',
                'Margie',
                'Nina',
                'Cassandra',
                'Leah',
                'Penny',
                'Kay',
                'Priscilla',
                'Naomi',
                'Carole',
                'Brandy',
                'Olga',
                'Billie',
                'Dianne',
                'Tracey',
                'Leona',
                'Jenny',
                'Felicia',
                'Sonia',
                'Miriam',
                'Velma',
                'Becky',
                'Bobbie',
                'Violet',
                'Kristina',
                'Toni',
                'Misty',
                'Mae',
                'Shelly',
                'Daisy',
                'Ramona',
                'Sherri',
                'Erika',
                'Katrina',
                'Claire',
                'Lindsey',
                'Lindsay',
                'Geneva',
                'Guadalupe',
                'Belinda',
                'Margarita',
                'Sheryl',
                'Cora',
                'Faye',
                'Ada',
                'Natasha',
                'Sabrina',
                'Isabel',
                'Marguerite',
                'Hattie',
                'Harriet',
                'Molly',
                'Cecilia',
                'Kristi',
                'Brandi',
                'Blanche',
                'Sandy',
                'Rosie',
                'Joanna',
                'Iris',
                'Eunice',
                'Angie',
                'Inez',
                'Lynda',
                'Madeline',
                'Amelia',
                'Alberta',
                'Genevieve',
                'Monique',
                'Jodi',
                'Janie',
                'Maggie',
                'Kayla',
                'Sonya',
                'Jan',
                'Lee',
                'Kristine',
                'Candace',
                'Fannie',
                'Maryann',
                'Opal',
                'Alison',
                'Yvette',
                'Melody',
                'Luz',
                'Susie',
                'Olivia',
                'Flora',
                'Shelley',
                'Kristy',
                'Mamie',
                'Lula',
                'Lola',
                'Verna',
                'Beulah',
                'Antoinette',
                'Candice',
                'Juana']

name_list = female_names + male_names


cities_and_states = ["Alabama",
                     "Alexander City",
                     "Andalusia",
                     "Anniston",
                     "Athens",
                     "Atmore",
                     "Auburn",
                     "Bessemer",
                     "Birmingham",
                     "Chickasaw",
                     "Clanton",
                     "Cullman",
                     "Decatur",
                     "Demopolis",
                     "Dothan",
                     "Enterprise",
                     "Eufaula",
                     "Florence",
                     "Fort Payne",
                     "Gadsden",
                     "Greenville",
                     "Guntersville",
                     "Huntsville",
                     "Jasper",
                     "Marion",
                     "Mobile",
                     "Montgomery",
                     "Opelika",
                     "Ozark",
                     "Phenix City",
                     "Prichard",
                     "Scottsboro",
                     "Selma",
                     "Sheffield",
                     "Sylacauga",
                     "Talladega",
                     "Troy",
                     "Tuscaloosa",
                     "Tuscumbia",
                     "Tuskegee",
                     "Alaska",
                     "Anchorage",
                     "Cordova",
                     "Fairbanks",
                     "Haines",
                     "Homer",
                     "Juneau",
                     "Ketchikan",
                     "Kodiak",
                     "Kotzebue",
                     "Nome",
                     "Palmer",
                     "Seward",
                     "Sitka",
                     "Skagway",
                     "Valdez",
                     "Arizona",
                     "Ajo",
                     "Avondale",
                     "Bisbee",
                     "Casa Grande",
                     "Chandler",
                     "Clifton",
                     "Douglas",
                     "Flagstaff",
                     "Florence",
                     "Gila Bend",
                     "Glendale",
                     "Globe",
                     "Kingman",
                     "Lake Havasu City",
                     "Mesa",
                     "Nogales",
                     "Oraibi",
                     "Phoenix",
                     "Prescott",
                     "Scottsdale",
                     "Sierra Vista",
                     "Tempe",
                     "Tombstone",
                     "Tucson",
                     "Walpi",
                     "Window Rock",
                     "Winslow",
                     "Yuma",
                     "Arkansas",
                     "Arkadelphia",
                     "Arkansas Post",
                     "Batesville",
                     "Benton",
                     "Blytheville",
                     "Camden",
                     "Conway",
                     "Crossett",
                     "El Dorado",
                     "Fayetteville",
                     "Forrest City",
                     "Fort Smith",
                     "Harrison",
                     "Helena",
                     "Hope",
                     "Hot Springs",
                     "Jacksonville",
                     "Jonesboro",
                     "Little Rock",
                     "Magnolia",
                     "Morrilton",
                     "Newport",
                     "North Little Rock",
                     "Osceola",
                     "Pine Bluff",
                     "Rogers",
                     "Searcy",
                     "Stuttgart",
                     "Van Buren",
                     "West Memphis",
                     "California",
                     "Alameda",
                     "Alhambra",
                     "Anaheim",
                     "Antioch",
                     "Arcadia",
                     "Bakersfield",
                     "Barstow",
                     "Belmont",
                     "Berkeley",
                     "Beverly Hills",
                     "Brea",
                     "Buena Park",
                     "Burbank",
                     "Calexico",
                     "Calistoga",
                     "Carlsbad",
                     "Carmel",
                     "Chico",
                     "Chula Vista",
                     "Claremont",
                     "Compton",
                     "Concord",
                     "Corona",
                     "Coronado",
                     "Costa Mesa",
                     "Culver City",
                     "Daly City",
                     "Davis",
                     "Downey",
                     "El Centro",
                     "El Cerrito",
                     "El Monte",
                     "Escondido",
                     "Eureka",
                     "Fairfield",
                     "Fontana",
                     "Fremont",
                     "Fresno",
                     "Fullerton",
                     "Garden Grove",
                     "Glendale",
                     "Hayward",
                     "Hollywood",
                     "Huntington Beach",
                     "Indio",
                     "Inglewood",
                     "Irvine",
                     "La Habra",
                     "Laguna Beach",
                     "Lancaster",
                     "Livermore",
                     "Lodi",
                     "Lompoc",
                     "Long Beach",
                     "Los Angeles",
                     "Malibu",
                     "Martinez",
                     "Marysville",
                     "Menlo Park",
                     "Merced",
                     "Modesto",
                     "Monterey",
                     "Mountain View",
                     "Napa",
                     "Needles",
                     "Newport Beach",
                     "Norwalk",
                     "Novato",
                     "Oakland",
                     "Oceanside",
                     "Ojai",
                     "Ontario",
                     "Orange",
                     "Oroville",
                     "Oxnard",
                     "Pacific Grove",
                     "Palm Springs",
                     "Palmdale",
                     "Palo Alto",
                     "Pasadena",
                     "Petaluma",
                     "Pomona",
                     "Port Hueneme",
                     "Rancho Cucamonga",
                     "Red Bluff",
                     "Redding",
                     "Redlands",
                     "Redondo Beach",
                     "Redwood City",
                     "Richmond",
                     "Riverside",
                     "Roseville",
                     "Sacramento",
                     "Salinas",
                     "San Bernardino",
                     "San Clemente",
                     "San Diego",
                     "San Fernando",
                     "San Francisco",
                     "San Gabriel",
                     "San Jose",
                     "San Juan Capistrano",
                     "San Leandro",
                     "San Luis Obispo",
                     "San Marino",
                     "San Mateo",
                     "San Pedro",
                     "San Rafael",
                     "San Simeon",
                     "Santa Ana",
                     "Santa Barbara",
                     "Santa Clara",
                     "Santa Clarita",
                     "Santa Cruz",
                     "Santa Monica",
                     "Santa Rosa",
                     "Sausalito",
                     "Simi Valley",
                     "Sonoma",
                     "South San Francisco",
                     "Stockton",
                     "Sunnyvale",
                     "Susanville",
                     "Thousand Oaks",
                     "Torrance",
                     "Turlock",
                     "Ukiah",
                     "Vallejo",
                     "Ventura",
                     "Victorville",
                     "Visalia",
                     "Walnut Creek",
                     "Watts",
                     "West Covina",
                     "Whittier",
                     "Woodland",
                     "Yorba Linda",
                     "Yuba City",
                     "Colorado",
                     "Alamosa",
                     "Aspen",
                     "Aurora",
                     "Boulder",
                     "Breckenridge",
                     "Brighton",
                     "Canon City",
                     "Central City",
                     "Climax",
                     "Colorado Springs",
                     "Cortez",
                     "Cripple Creek",
                     "Denver",
                     "Durango",
                     "Englewood",
                     "Estes Park",
                     "Fort Collins",
                     "Fort Morgan",
                     "Georgetown",
                     "Glenwood Springs",
                     "Golden",
                     "Grand Junction",
                     "Greeley",
                     "Gunnison",
                     "La Junta",
                     "Leadville",
                     "Littleton",
                     "Longmont",
                     "Loveland",
                     "Montrose",
                     "Ouray",
                     "Pagosa Springs",
                     "Pueblo",
                     "Silverton",
                     "Steamboat Springs",
                     "Sterling",
                     "Telluride",
                     "Trinidad",
                     "Vail",
                     "Walsenburg",
                     "Westminster",
                     "Connecticut",
                     "Ansonia",
                     "Berlin",
                     "Bloomfield",
                     "Branford",
                     "Bridgeport",
                     "Bristol",
                     "Coventry",
                     "Danbury",
                     "Darien",
                     "Derby",
                     "East Hartford",
                     "East Haven",
                     "Enfield",
                     "Fairfield",
                     "Farmington",
                     "Greenwich",
                     "Groton",
                     "Guilford",
                     "Hamden",
                     "Hartford",
                     "Lebanon",
                     "Litchfield",
                     "Manchester",
                     "Mansfield",
                     "Meriden",
                     "Middletown",
                     "Milford",
                     "Mystic",
                     "Naugatuck",
                     "New Britain",
                     "New Haven",
                     "New London",
                     "North Haven",
                     "Norwalk",
                     "Norwich",
                     "Old Saybrook",
                     "Orange",
                     "Seymour",
                     "Shelton",
                     "Simsbury",
                     "Southington",
                     "Stamford",
                     "Stonington",
                     "Stratford",
                     "Torrington",
                     "Wallingford",
                     "Waterbury",
                     "Waterford",
                     "Watertown",
                     "West Hartford",
                     "West Haven",
                     "Westport",
                     "Wethersfield",
                     "Willimantic",
                     "Windham",
                     "Windsor",
                     "Windsor Locks",
                     "Winsted",
                     "Delaware",
                     "Dover",
                     "Lewes",
                     "Milford",
                     "New Castle",
                     "Newark",
                     "Smyrna",
                     "Wilmington",
                     "Florida",
                     "Apalachicola",
                     "Bartow",
                     "Belle Glade",
                     "Boca Raton",
                     "Bradenton",
                     "Cape Coral",
                     "Clearwater",
                     "Cocoa Beach",
                     "Cocoa-Rockledge",
                     "Coral Gables",
                     "Daytona Beach",
                     "De Land",
                     "Deerfield Beach",
                     "Delray Beach",
                     "Fernandina Beach",
                     "Fort Lauderdale",
                     "Fort Myers",
                     "Fort Pierce",
                     "Fort Walton Beach",
                     "Gainesville",
                     "Hallandale Beach",
                     "Hialeah",
                     "Hollywood",
                     "Homestead",
                     "Jacksonville",
                     "Key West",
                     "Lake City",
                     "Lake Wales",
                     "Lakeland",
                     "Largo",
                     "Melbourne",
                     "Miami",
                     "Miami Beach",
                     "Naples",
                     "New Smyrna Beach",
                     "Ocala",
                     "Orlando",
                     "Ormond Beach",
                     "Palatka",
                     "Palm Bay",
                     "Palm Beach",
                     "Panama City",
                     "Pensacola",
                     "Pompano Beach",
                     "Saint Augustine",
                     "Saint Petersburg",
                     "Sanford",
                     "Sarasota",
                     "Sebring",
                     "Tallahassee",
                     "Tampa",
                     "Tarpon Springs",
                     "Titusville",
                     "Venice",
                     "West Palm Beach",
                     "White Springs",
                     "Winter Haven",
                     "Winter Park",
                     "Georgia",
                     "Albany",
                     "Americus",
                     "Andersonville",
                     "Athens",
                     "Atlanta",
                     "Augusta",
                     "Bainbridge",
                     "Blairsville",
                     "Brunswick",
                     "Calhoun",
                     "Carrollton",
                     "Columbus",
                     "Dahlonega",
                     "Dalton",
                     "Darien",
                     "Decatur",
                     "Douglas",
                     "East Point",
                     "Fitzgerald",
                     "Fort Valley",
                     "Gainesville",
                     "La Grange",
                     "Macon",
                     "Marietta",
                     "Milledgeville",
                     "Plains",
                     "Rome",
                     "Savannah",
                     "Toccoa",
                     "Valdosta",
                     "Warm Springs",
                     "Warner Robins",
                     "Washington",
                     "Waycross",
                     "Hawaii",
                     "Hanalei",
                     "Hilo",
                     "Honaunau",
                     "Honolulu",
                     "Kahului",
                     "Kaneohe",
                     "Kapaa",
                     "Kawaihae",
                     "Lahaina",
                     "Laie",
                     "Wahiawa",
                     "Wailuku",
                     "Waimea",
                     "Idaho",
                     "Blackfoot",
                     "Boise",
                     "Bonners Ferry",
                     "Caldwell",
                     "Coeur d’Alene",
                     "Idaho City",
                     "Idaho Falls",
                     "Kellogg",
                     "Lewiston",
                     "Moscow",
                     "Nampa",
                     "Pocatello",
                     "Priest River",
                     "Rexburg",
                     "Sun Valley",
                     "Twin Falls",
                     "Illinois",
                     "Alton",
                     "Arlington Heights",
                     "Arthur",
                     "Aurora",
                     "Belleville",
                     "Belvidere",
                     "Bloomington",
                     "Brookfield",
                     "Cahokia",
                     "Cairo",
                     "Calumet City",
                     "Canton",
                     "Carbondale",
                     "Carlinville",
                     "Carthage",
                     "Centralia",
                     "Champaign",
                     "Charleston",
                     "Chester",
                     "Chicago",
                     "Chicago Heights",
                     "Cicero",
                     "Collinsville",
                     "Danville",
                     "Decatur",
                     "DeKalb",
                     "Des Plaines",
                     "Dixon",
                     "East Moline",
                     "East Saint Louis",
                     "Effingham",
                     "Elgin",
                     "Elmhurst",
                     "Evanston",
                     "Freeport",
                     "Galena",
                     "Galesburg",
                     "Glen Ellyn",
                     "Glenview",
                     "Granite City",
                     "Harrisburg",
                     "Herrin",
                     "Highland Park",
                     "Jacksonville",
                     "Joliet",
                     "Kankakee",
                     "Kaskaskia",
                     "Kewanee",
                     "La Salle",
                     "Lake Forest",
                     "Libertyville",
                     "Lincoln",
                     "Lisle",
                     "Lombard",
                     "Macomb",
                     "Mattoon",
                     "Moline",
                     "Monmouth",
                     "Mount Vernon",
                     "Mundelein",
                     "Naperville",
                     "Nauvoo",
                     "Normal",
                     "North Chicago",
                     "Oak Park",
                     "Oregon",
                     "Ottawa",
                     "Palatine",
                     "Park Forest",
                     "Park Ridge",
                     "Pekin",
                     "Peoria",
                     "Petersburg",
                     "Pontiac",
                     "Quincy",
                     "Rantoul",
                     "River Forest",
                     "Rock Island",
                     "Rockford",
                     "Salem",
                     "Shawneetown",
                     "Skokie",
                     "South Holland",
                     "Springfield",
                     "Streator",
                     "Summit",
                     "Urbana",
                     "Vandalia",
                     "Virden",
                     "Waukegan",
                     "Wheaton",
                     "Wilmette",
                     "Winnetka",
                     "Wood River",
                     "Zion",
                     "Indiana",
                     "Anderson",
                     "Bedford",
                     "Bloomington",
                     "Columbus",
                     "Connersville",
                     "Corydon",
                     "Crawfordsville",
                     "East Chicago",
                     "Elkhart",
                     "Elwood",
                     "Evansville",
                     "Fort Wayne",
                     "French Lick",
                     "Gary",
                     "Geneva",
                     "Goshen",
                     "Greenfield",
                     "Hammond",
                     "Hobart",
                     "Huntington",
                     "Indianapolis",
                     "Jeffersonville",
                     "Kokomo",
                     "Lafayette",
                     "Madison",
                     "Marion",
                     "Michigan City",
                     "Mishawaka",
                     "Muncie",
                     "Nappanee",
                     "Nashville",
                     "New Albany",
                     "New Castle",
                     "New Harmony",
                     "Peru",
                     "Plymouth",
                     "Richmond",
                     "Santa Claus",
                     "Shelbyville",
                     "South Bend",
                     "Terre Haute",
                     "Valparaiso",
                     "Vincennes",
                     "Wabash",
                     "West Lafayette",
                     "Iowa",
                     "Amana Colonies",
                     "Ames",
                     "Boone",
                     "Burlington",
                     "Cedar Falls",
                     "Cedar Rapids",
                     "Charles City",
                     "Cherokee",
                     "Clinton",
                     "Council Bluffs",
                     "Davenport",
                     "Des Moines",
                     "Dubuque",
                     "Estherville",
                     "Fairfield",
                     "Fort Dodge",
                     "Grinnell",
                     "Indianola",
                     "Iowa City",
                     "Keokuk",
                     "Mason City",
                     "Mount Pleasant",
                     "Muscatine",
                     "Newton",
                     "Oskaloosa",
                     "Ottumwa",
                     "Sioux City",
                     "Waterloo",
                     "Webster City",
                     "West Des Moines",
                     "Kansas",
                     "Abilene",
                     "Arkansas City",
                     "Atchison",
                     "Chanute",
                     "Coffeyville",
                     "Council Grove",
                     "Dodge City",
                     "Emporia",
                     "Fort Scott",
                     "Garden City",
                     "Great Bend",
                     "Hays",
                     "Hutchinson",
                     "Independence",
                     "Junction City",
                     "Kansas City",
                     "Lawrence",
                     "Leavenworth",
                     "Liberal",
                     "Manhattan",
                     "McPherson",
                     "Medicine Lodge",
                     "Newton",
                     "Olathe",
                     "Osawatomie",
                     "Ottawa",
                     "Overland Park",
                     "Pittsburg",
                     "Salina",
                     "Shawnee",
                     "Smith Center",
                     "Topeka",
                     "Wichita",
                     "Kentucky",
                     "Ashland",
                     "Barbourville",
                     "Bardstown",
                     "Berea",
                     "Boonesborough",
                     "Bowling Green",
                     "Campbellsville",
                     "Covington",
                     "Danville",
                     "Elizabethtown",
                     "Frankfort",
                     "Harlan",
                     "Harrodsburg",
                     "Hazard",
                     "Henderson",
                     "Hodgenville",
                     "Hopkinsville",
                     "Lexington",
                     "Louisville",
                     "Mayfield",
                     "Maysville",
                     "Middlesboro",
                     "Newport",
                     "Owensboro",
                     "Paducah",
                     "Paris",
                     "Richmond",
                     "Louisiana",
                     "Abbeville",
                     "Alexandria",
                     "Bastrop",
                     "Baton Rouge",
                     "Bogalusa",
                     "Bossier City",
                     "Gretna",
                     "Houma",
                     "Lafayette",
                     "Lake Charles",
                     "Monroe",
                     "Morgan City",
                     "Natchitoches",
                     "New Iberia",
                     "New Orleans",
                     "Opelousas",
                     "Ruston",
                     "Saint Martinville",
                     "Shreveport",
                     "Thibodaux",
                     "Maine",
                     "Auburn",
                     "Augusta",
                     "Bangor",
                     "Bar Harbor",
                     "Bath",
                     "Belfast",
                     "Biddeford",
                     "Boothbay Harbor",
                     "Brunswick",
                     "Calais",
                     "Caribou",
                     "Castine",
                     "Eastport",
                     "Ellsworth",
                     "Farmington",
                     "Fort Kent",
                     "Gardiner",
                     "Houlton",
                     "Kennebunkport",
                     "Kittery",
                     "Lewiston",
                     "Lubec",
                     "Machias",
                     "Orono",
                     "Portland",
                     "Presque Isle",
                     "Rockland",
                     "Rumford",
                     "Saco",
                     "Scarborough",
                     "Waterville",
                     "York",
                     "Maryland",
                     "Aberdeen",
                     "Annapolis",
                     "Baltimore",
                     "Bethesda-Chevy Chase",
                     "Bowie",
                     "Cambridge",
                     "Catonsville",
                     "College Park",
                     "Columbia",
                     "Cumberland",
                     "Easton",
                     "Elkton",
                     "Emmitsburg",
                     "Frederick",
                     "Greenbelt",
                     "Hagerstown",
                     "Hyattsville",
                     "Laurel",
                     "Oakland",
                     "Ocean City",
                     "Rockville",
                     "Saint Marys City",
                     "Salisbury",
                     "Silver Spring",
                     "Takoma Park",
                     "Towson",
                     "Westminster",
                     "Massachusetts",
                     "Abington",
                     "Adams",
                     "Amesbury",
                     "Amherst",
                     "Andover",
                     "Arlington",
                     "Athol",
                     "Attleboro",
                     "Barnstable",
                     "Bedford",
                     "Beverly",
                     "Boston",
                     "Bourne",
                     "Braintree",
                     "Brockton",
                     "Brookline",
                     "Cambridge",
                     "Canton",
                     "Charlestown",
                     "Chelmsford",
                     "Chelsea",
                     "Chicopee",
                     "Clinton",
                     "Cohasset",
                     "Concord",
                     "Danvers",
                     "Dartmouth",
                     "Dedham",
                     "Dennis",
                     "Duxbury",
                     "Eastham",
                     "Edgartown",
                     "Everett",
                     "Fairhaven",
                     "Fall River",
                     "Falmouth",
                     "Fitchburg",
                     "Framingham",
                     "Gloucester",
                     "Great Barrington",
                     "Greenfield",
                     "Groton",
                     "Harwich",
                     "Haverhill",
                     "Hingham",
                     "Holyoke",
                     "Hyannis",
                     "Ipswich",
                     "Lawrence",
                     "Lenox",
                     "Leominster",
                     "Lexington",
                     "Lowell",
                     "Ludlow",
                     "Lynn",
                     "Malden",
                     "Marblehead",
                     "Marlborough",
                     "Medford",
                     "Milton",
                     "Nahant",
                     "Natick",
                     "New Bedford",
                     "Newburyport",
                     "Newton",
                     "North Adams",
                     "Northampton",
                     "Norton",
                     "Norwood",
                     "Peabody",
                     "Pittsfield",
                     "Plymouth",
                     "Provincetown",
                     "Quincy",
                     "Randolph",
                     "Revere",
                     "Salem",
                     "Sandwich",
                     "Saugus",
                     "Somerville",
                     "South Hadley",
                     "Springfield",
                     "Stockbridge",
                     "Stoughton",
                     "Sturbridge",
                     "Sudbury",
                     "Taunton",
                     "Tewksbury",
                     "Truro",
                     "Watertown",
                     "Webster",
                     "Wellesley",
                     "Wellfleet",
                     "West Bridgewater",
                     "West Springfield",
                     "Westfield",
                     "Weymouth",
                     "Whitman",
                     "Williamstown",
                     "Woburn",
                     "Woods Hole",
                     "Worcester",
                     "Michigan",
                     "Adrian",
                     "Alma",
                     "Ann Arbor",
                     "Battle Creek",
                     "Bay City",
                     "Benton Harbor",
                     "Bloomfield Hills",
                     "Cadillac",
                     "Charlevoix",
                     "Cheboygan",
                     "Dearborn",
                     "Detroit",
                     "East Lansing",
                     "Eastpointe",
                     "Ecorse",
                     "Escanaba",
                     "Flint",
                     "Grand Haven",
                     "Grand Rapids",
                     "Grayling",
                     "Grosse Pointe",
                     "Hancock",
                     "Highland Park",
                     "Holland",
                     "Houghton",
                     "Interlochen",
                     "Iron Mountain",
                     "Ironwood",
                     "Ishpeming",
                     "Jackson",
                     "Kalamazoo",
                     "Lansing",
                     "Livonia",
                     "Ludington",
                     "Mackinaw City",
                     "Manistee",
                     "Marquette",
                     "Menominee",
                     "Midland",
                     "Monroe",
                     "Mount Clemens",
                     "Mount Pleasant",
                     "Muskegon",
                     "Niles",
                     "Petoskey",
                     "Pontiac",
                     "Port Huron",
                     "Royal Oak",
                     "Saginaw",
                     "Saint Ignace",
                     "Saint Joseph",
                     "Sault Sainte Marie",
                     "Traverse City",
                     "Trenton",
                     "Warren",
                     "Wyandotte",
                     "Ypsilanti",
                     "Minnesota",
                     "Albert Lea",
                     "Alexandria",
                     "Austin",
                     "Bemidji",
                     "Bloomington",
                     "Brainerd",
                     "Crookston",
                     "Duluth",
                     "Ely",
                     "Eveleth",
                     "Faribault",
                     "Fergus Falls",
                     "Hastings",
                     "Hibbing",
                     "International Falls",
                     "Little Falls",
                     "Mankato",
                     "Minneapolis",
                     "Moorhead",
                     "New Ulm",
                     "Northfield",
                     "Owatonna",
                     "Pipestone",
                     "Red Wing",
                     "Rochester",
                     "Saint Cloud",
                     "Saint Paul",
                     "Sauk Centre",
                     "South Saint Paul",
                     "Stillwater",
                     "Virginia",
                     "Willmar",
                     "Winona",
                     "Mississippi",
                     "Bay Saint Louis",
                     "Biloxi",
                     "Canton",
                     "Clarksdale",
                     "Columbia",
                     "Columbus",
                     "Corinth",
                     "Greenville",
                     "Greenwood",
                     "Grenada",
                     "Gulfport",
                     "Hattiesburg",
                     "Holly Springs",
                     "Jackson",
                     "Laurel",
                     "Meridian",
                     "Natchez",
                     "Ocean Springs",
                     "Oxford",
                     "Pascagoula",
                     "Pass Christian",
                     "Philadelphia",
                     "Port Gibson",
                     "Starkville",
                     "Tupelo",
                     "Vicksburg",
                     "West Point",
                     "Yazoo City",
                     "Missouri",
                     "Boonville",
                     "Branson",
                     "Cape Girardeau",
                     "Carthage",
                     "Chillicothe",
                     "Clayton",
                     "Columbia",
                     "Excelsior Springs",
                     "Ferguson",
                     "Florissant",
                     "Fulton",
                     "Hannibal",
                     "Independence",
                     "Jefferson City",
                     "Joplin",
                     "Kansas City",
                     "Kirksville",
                     "Lamar",
                     "Lebanon",
                     "Lexington",
                     "Maryville",
                     "Mexico",
                     "Monett",
                     "Neosho",
                     "New Madrid",
                     "Rolla",
                     "Saint Charles",
                     "Saint Joseph",
                     "Saint Louis",
                     "Sainte Genevieve",
                     "Salem",
                     "Sedalia",
                     "Springfield",
                     "Warrensburg",
                     "West Plains",
                     "Montana",
                     "Anaconda",
                     "Billings",
                     "Bozeman",
                     "Butte",
                     "Dillon",
                     "Fort Benton",
                     "Glendive",
                     "Great Falls",
                     "Havre",
                     "Helena",
                     "Kalispell",
                     "Lewistown",
                     "Livingston",
                     "Miles City",
                     "Missoula",
                     "Virginia City",
                     "Nebraska",
                     "Beatrice",
                     "Bellevue",
                     "Boys Town",
                     "Chadron",
                     "Columbus",
                     "Fremont",
                     "Grand Island",
                     "Hastings",
                     "Kearney",
                     "Lincoln",
                     "McCook",
                     "Minden",
                     "Nebraska City",
                     "Norfolk",
                     "North Platte",
                     "Omaha",
                     "Plattsmouth",
                     "Red Cloud",
                     "Sidney",
                     "Nevada",
                     "Boulder City",
                     "Carson City",
                     "Elko",
                     "Ely",
                     "Fallon",
                     "Genoa",
                     "Goldfield",
                     "Henderson",
                     "Las Vegas",
                     "North Las Vegas",
                     "Reno",
                     "Sparks",
                     "Virginia City",
                     "Winnemucca",
                     "New Hampshire",
                     "Berlin",
                     "Claremont",
                     "Concord",
                     "Derry",
                     "Dover",
                     "Durham",
                     "Exeter",
                     "Franklin",
                     "Hanover",
                     "Hillsborough",
                     "Keene",
                     "Laconia",
                     "Lebanon",
                     "Manchester",
                     "Nashua",
                     "Peterborough",
                     "Plymouth",
                     "Portsmouth",
                     "Rochester",
                     "Salem",
                     "Somersworth",
                     "New Jersey",
                     "Asbury Park",
                     "Atlantic City",
                     "Bayonne",
                     "Bloomfield",
                     "Bordentown",
                     "Bound Brook",
                     "Bridgeton",
                     "Burlington",
                     "Caldwell",
                     "Camden",
                     "Cape May",
                     "Clifton",
                     "Cranford",
                     "East Orange",
                     "Edison",
                     "Elizabeth",
                     "Englewood",
                     "Fort Lee",
                     "Glassboro",
                     "Hackensack",
                     "Haddonfield",
                     "Hoboken",
                     "Irvington",
                     "Jersey City",
                     "Lakehurst",
                     "Lakewood",
                     "Long Beach",
                     "Long Branch",
                     "Madison",
                     "Menlo Park",
                     "Millburn",
                     "Millville",
                     "Montclair",
                     "Morristown",
                     "Mount Holly",
                     "New Brunswick",
                     "New Milford",
                     "Newark",
                     "Ocean City",
                     "Orange",
                     "Parsippany–Troy Hills",
                     "Passaic",
                     "Paterson",
                     "Perth Amboy",
                     "Plainfield",
                     "Princeton",
                     "Ridgewood",
                     "Roselle",
                     "Rutherford",
                     "Salem",
                     "Somerville",
                     "South Orange Village",
                     "Totowa",
                     "Trenton",
                     "Union",
                     "Union City",
                     "Vineland",
                     "Wayne",
                     "Weehawken",
                     "West New York",
                     "West Orange",
                     "Willingboro",
                     "Woodbridge",
                     "New Mexico",
                     "Acoma",
                     "Alamogordo",
                     "Albuquerque",
                     "Artesia",
                     "Belen",
                     "Carlsbad",
                     "Clovis",
                     "Deming",
                     "Farmington",
                     "Gallup",
                     "Grants",
                     "Hobbs",
                     "Las Cruces",
                     "Las Vegas",
                     "Los Alamos",
                     "Lovington",
                     "Portales",
                     "Raton",
                     "Roswell",
                     "Santa Fe",
                     "Shiprock",
                     "Silver City",
                     "Socorro",
                     "Taos",
                     "Truth or Consequences",
                     "Tucumcari",
                     "New York",
                     "Albany",
                     "Amsterdam",
                     "Auburn",
                     "Babylon",
                     "Batavia",
                     "Beacon",
                     "Bedford",
                     "Binghamton",
                     "Bronx",
                     "Brooklyn",
                     "Buffalo",
                     "Chautauqua",
                     "Cheektowaga",
                     "Clinton",
                     "Cohoes",
                     "Coney Island",
                     "Cooperstown",
                     "Corning",
                     "Cortland",
                     "Crown Point",
                     "Dunkirk",
                     "East Aurora",
                     "East Hampton",
                     "Eastchester",
                     "Elmira",
                     "Flushing",
                     "Forest Hills",
                     "Fredonia",
                     "Garden City",
                     "Geneva",
                     "Glens Falls",
                     "Gloversville",
                     "Great Neck",
                     "Hammondsport",
                     "Harlem",
                     "Hempstead",
                     "Herkimer",
                     "Hudson",
                     "Huntington",
                     "Hyde Park",
                     "Ilion",
                     "Ithaca",
                     "Jamestown",
                     "Johnstown",
                     "Kingston",
                     "Lackawanna",
                     "Lake Placid",
                     "Levittown",
                     "Lockport",
                     "Mamaroneck",
                     "Manhattan",
                     "Massena",
                     "Middletown",
                     "Mineola",
                     "Mount Vernon",
                     "New Paltz",
                     "New Rochelle",
                     "New Windsor",
                     "New York City",
                     "Newburgh",
                     "Niagara Falls",
                     "North Hempstead",
                     "Nyack",
                     "Ogdensburg",
                     "Olean",
                     "Oneida",
                     "Oneonta",
                     "Ossining",
                     "Oswego",
                     "Oyster Bay",
                     "Palmyra",
                     "Peekskill",
                     "Plattsburgh",
                     "Port Washington",
                     "Potsdam",
                     "Poughkeepsie",
                     "Queens",
                     "Rensselaer",
                     "Rochester",
                     "Rome",
                     "Rotterdam",
                     "Rye",
                     "Sag Harbor",
                     "Saranac Lake",
                     "Saratoga Springs",
                     "Scarsdale",
                     "Schenectady",
                     "Seneca Falls",
                     "Southampton",
                     "Staten Island",
                     "Stony Brook",
                     "Stony Point",
                     "Syracuse",
                     "Tarrytown",
                     "Ticonderoga",
                     "Tonawanda",
                     "Troy",
                     "Utica",
                     "Watertown",
                     "Watervliet",
                     "Watkins Glen",
                     "West Seneca",
                     "White Plains",
                     "Woodstock",
                     "Yonkers",
                     "North Carolina",
                     "Asheboro",
                     "Asheville",
                     "Bath",
                     "Beaufort",
                     "Boone",
                     "Burlington",
                     "Chapel Hill",
                     "Charlotte",
                     "Concord",
                     "Durham",
                     "Edenton",
                     "Elizabeth City",
                     "Fayetteville",
                     "Gastonia",
                     "Goldsboro",
                     "Greensboro",
                     "Greenville",
                     "Halifax",
                     "Henderson",
                     "Hickory",
                     "High Point",
                     "Hillsborough",
                     "Jacksonville",
                     "Kinston",
                     "Kitty Hawk",
                     "Lumberton",
                     "Morehead City",
                     "Morganton",
                     "Nags Head",
                     "New Bern",
                     "Pinehurst",
                     "Raleigh",
                     "Rocky Mount",
                     "Salisbury",
                     "Shelby",
                     "Washington",
                     "Wilmington",
                     "Wilson",
                     "Winston-Salem",
                     "North Dakota",
                     "Bismarck",
                     "Devils Lake",
                     "Dickinson",
                     "Fargo",
                     "Grand Forks",
                     "Jamestown",
                     "Mandan",
                     "Minot",
                     "Rugby",
                     "Valley City",
                     "Wahpeton",
                     "Williston",
                     "Ohio",
                     "Akron",
                     "Alliance",
                     "Ashtabula",
                     "Athens",
                     "Barberton",
                     "Bedford",
                     "Bellefontaine",
                     "Bowling Green",
                     "Canton",
                     "Chillicothe",
                     "Cincinnati",
                     "Cleveland",
                     "Cleveland Heights",
                     "Columbus",
                     "Conneaut",
                     "Cuyahoga Falls",
                     "Dayton",
                     "Defiance",
                     "Delaware",
                     "East Cleveland",
                     "East Liverpool",
                     "Elyria",
                     "Euclid",
                     "Findlay",
                     "Gallipolis",
                     "Greenville",
                     "Hamilton",
                     "Kent",
                     "Kettering",
                     "Lakewood",
                     "Lancaster",
                     "Lima",
                     "Lorain",
                     "Mansfield",
                     "Marietta",
                     "Marion",
                     "Martins Ferry",
                     "Massillon",
                     "Mentor",
                     "Middletown",
                     "Milan",
                     "Mount Vernon",
                     "New Philadelphia",
                     "Newark",
                     "Niles",
                     "North College Hill",
                     "Norwalk",
                     "Oberlin",
                     "Painesville",
                     "Parma",
                     "Piqua",
                     "Portsmouth",
                     "Put-in-Bay",
                     "Salem",
                     "Sandusky",
                     "Shaker Heights",
                     "Springfield",
                     "Steubenville",
                     "Tiffin",
                     "Toledo",
                     "Urbana",
                     "Warren",
                     "Wooster",
                     "Worthington",
                     "Xenia",
                     "Yellow Springs",
                     "Youngstown",
                     "Zanesville",
                     "Oklahoma",
                     "Ada",
                     "Altus",
                     "Alva",
                     "Anadarko",
                     "Ardmore",
                     "Bartlesville",
                     "Bethany",
                     "Chickasha",
                     "Claremore",
                     "Clinton",
                     "Cushing",
                     "Duncan",
                     "Durant",
                     "Edmond",
                     "El Reno",
                     "Elk City",
                     "Enid",
                     "Eufaula",
                     "Frederick",
                     "Guthrie",
                     "Guymon",
                     "Hobart",
                     "Holdenville",
                     "Hugo",
                     "Lawton",
                     "McAlester",
                     "Miami",
                     "Midwest City",
                     "Moore",
                     "Muskogee",
                     "Norman",
                     "Oklahoma City",
                     "Okmulgee",
                     "Pauls Valley",
                     "Pawhuska",
                     "Perry",
                     "Ponca City",
                     "Pryor",
                     "Sallisaw",
                     "Sand Springs",
                     "Sapulpa",
                     "Seminole",
                     "Shawnee",
                     "Stillwater",
                     "Tahlequah",
                     "The Village",
                     "Tulsa",
                     "Vinita",
                     "Wewoka",
                     "Woodward",
                     "Oregon",
                     "Albany",
                     "Ashland",
                     "Astoria",
                     "Baker City",
                     "Beaverton",
                     "Bend",
                     "Brookings",
                     "Burns",
                     "Coos Bay",
                     "Corvallis",
                     "Eugene",
                     "Grants Pass",
                     "Hillsboro",
                     "Hood River",
                     "Jacksonville",
                     "John Day",
                     "Klamath Falls",
                     "La Grande",
                     "Lake Oswego",
                     "Lakeview",
                     "McMinnville",
                     "Medford",
                     "Newberg",
                     "Newport",
                     "Ontario",
                     "Oregon City",
                     "Pendleton",
                     "Port Orford",
                     "Portland",
                     "Prineville",
                     "Redmond",
                     "Reedsport",
                     "Roseburg",
                     "Salem",
                     "Seaside",
                     "Springfield",
                     "The Dalles",
                     "Tillamook",
                     "Pennsylvania",
                     "Abington",
                     "Aliquippa",
                     "Allentown",
                     "Altoona",
                     "Ambridge",
                     "Bedford",
                     "Bethlehem",
                     "Bloomsburg",
                     "Bradford",
                     "Bristol",
                     "Carbondale",
                     "Carlisle",
                     "Chambersburg",
                     "Chester",
                     "Columbia",
                     "Easton",
                     "Erie",
                     "Franklin",
                     "Germantown",
                     "Gettysburg",
                     "Greensburg",
                     "Hanover",
                     "Harmony",
                     "Harrisburg",
                     "Hazleton",
                     "Hershey",
                     "Homestead",
                     "Honesdale",
                     "Indiana",
                     "Jeannette",
                     "Jim Thorpe",
                     "Johnstown",
                     "Lancaster",
                     "Lebanon",
                     "Levittown",
                     "Lewistown",
                     "Lock Haven",
                     "Lower Southampton",
                     "McKeesport",
                     "Meadville",
                     "Middletown",
                     "Monroeville",
                     "Nanticoke",
                     "New Castle",
                     "New Hope",
                     "New Kensington",
                     "Norristown",
                     "Oil City",
                     "Philadelphia",
                     "Phoenixville",
                     "Pittsburgh",
                     "Pottstown",
                     "Pottsville",
                     "Reading",
                     "Scranton",
                     "Shamokin",
                     "Sharon",
                     "State College",
                     "Stroudsburg",
                     "Sunbury",
                     "Swarthmore",
                     "Tamaqua",
                     "Titusville",
                     "Uniontown",
                     "Warren",
                     "Washington",
                     "West Chester",
                     "Wilkes-Barre",
                     "Williamsport",
                     "York",
                     "Rhode Island",
                     "Barrington",
                     "Bristol",
                     "Central Falls",
                     "Cranston",
                     "East Greenwich",
                     "East Providence",
                     "Kingston",
                     "Middletown",
                     "Narragansett",
                     "Newport",
                     "North Kingstown",
                     "Pawtucket",
                     "Portsmouth",
                     "Providence",
                     "South Kingstown",
                     "Tiverton",
                     "Warren",
                     "Warwick",
                     "Westerly",
                     "Wickford",
                     "Woonsocket",
                     "South Carolina",
                     "Abbeville",
                     "Aiken",
                     "Anderson",
                     "Beaufort",
                     "Camden",
                     "Charleston",
                     "Columbia",
                     "Darlington",
                     "Florence",
                     "Gaffney",
                     "Georgetown",
                     "Greenville",
                     "Greenwood",
                     "Hartsville",
                     "Lancaster",
                     "Mount Pleasant",
                     "Myrtle Beach",
                     "Orangeburg",
                     "Rock Hill",
                     "Spartanburg",
                     "Sumter",
                     "Union",
                     "South Dakota",
                     "Aberdeen",
                     "Belle Fourche",
                     "Brookings",
                     "Canton",
                     "Custer",
                     "De Smet",
                     "Deadwood",
                     "Hot Springs",
                     "Huron",
                     "Lead",
                     "Madison",
                     "Milbank",
                     "Mitchell",
                     "Mobridge",
                     "Pierre",
                     "Rapid City",
                     "Sioux Falls",
                     "Spearfish",
                     "Sturgis",
                     "Vermillion",
                     "Watertown",
                     "Yankton",
                     "Tennessee",
                     "Alcoa",
                     "Athens",
                     "Chattanooga",
                     "Clarksville",
                     "Cleveland",
                     "Columbia",
                     "Cookeville",
                     "Dayton",
                     "Elizabethton",
                     "Franklin",
                     "Gallatin",
                     "Gatlinburg",
                     "Greeneville",
                     "Jackson",
                     "Johnson City",
                     "Jonesborough",
                     "Kingsport",
                     "Knoxville",
                     "Lebanon",
                     "Maryville",
                     "Memphis",
                     "Morristown",
                     "Murfreesboro",
                     "Nashville",
                     "Norris",
                     "Oak Ridge",
                     "Shelbyville",
                     "Tullahoma",
                     "Texas",
                     "Abilene",
                     "Alpine",
                     "Amarillo",
                     "Arlington",
                     "Austin",
                     "Baytown",
                     "Beaumont",
                     "Big Spring",
                     "Borger",
                     "Brownsville",
                     "Bryan",
                     "Canyon",
                     "Cleburne",
                     "College Station",
                     "Corpus Christi",
                     "Crystal City",
                     "Dallas",
                     "Del Rio",
                     "Denison",
                     "Denton",
                     "Eagle Pass",
                     "Edinburg",
                     "El Paso",
                     "Fort Worth",
                     "Freeport",
                     "Galveston",
                     "Garland",
                     "Goliad",
                     "Greenville",
                     "Harlingen",
                     "Houston",
                     "Huntsville",
                     "Irving",
                     "Johnson City",
                     "Kilgore",
                     "Killeen",
                     "Kingsville",
                     "Laredo",
                     "Longview",
                     "Lubbock",
                     "Lufkin",
                     "Marshall",
                     "McAllen",
                     "McKinney",
                     "Mesquite",
                     "Midland",
                     "Mission",
                     "Nacogdoches",
                     "New Braunfels",
                     "Odessa",
                     "Orange",
                     "Pampa",
                     "Paris",
                     "Pasadena",
                     "Pecos",
                     "Pharr",
                     "Plainview",
                     "Plano",
                     "Port Arthur",
                     "Port Lavaca",
                     "Richardson",
                     "San Angelo",
                     "San Antonio",
                     "San Felipe",
                     "San Marcos",
                     "Sherman",
                     "Sweetwater",
                     "Temple",
                     "Texarkana",
                     "Texas City",
                     "Tyler",
                     "Uvalde",
                     "Victoria",
                     "Waco",
                     "Weatherford",
                     "Wichita Falls",
                     "Ysleta",
                     "Utah",
                     "Alta",
                     "American Fork",
                     "Bountiful",
                     "Brigham City",
                     "Cedar City",
                     "Clearfield",
                     "Delta",
                     "Fillmore",
                     "Green River",
                     "Heber City",
                     "Kanab",
                     "Layton",
                     "Lehi",
                     "Logan",
                     "Manti",
                     "Moab",
                     "Monticello",
                     "Murray",
                     "Nephi",
                     "Ogden",
                     "Orderville",
                     "Orem",
                     "Panguitch",
                     "Park City",
                     "Payson",
                     "Price",
                     "Provo",
                     "Saint George",
                     "Salt Lake City",
                     "Spanish Fork",
                     "Springville",
                     "Tooele",
                     "Vernal",
                     "Vermont",
                     "Barre",
                     "Bellows Falls",
                     "Bennington",
                     "Brattleboro",
                     "Burlington",
                     "Essex",
                     "Manchester",
                     "Middlebury",
                     "Montpelier",
                     "Newport",
                     "Plymouth",
                     "Rutland",
                     "Saint Albans",
                     "Saint Johnsbury",
                     "Sharon",
                     "Winooski",
                     "Virginia",
                     "Abingdon",
                     "Alexandria",
                     "Bristol",
                     "Charlottesville",
                     "Chesapeake",
                     "Danville",
                     "Fairfax",
                     "Falls Church",
                     "Fredericksburg",
                     "Hampton",
                     "Hanover",
                     "Hopewell",
                     "Lexington",
                     "Lynchburg",
                     "Manassas",
                     "Martinsville",
                     "New Market",
                     "Newport News",
                     "Norfolk",
                     "Petersburg",
                     "Portsmouth",
                     "Reston",
                     "Richmond",
                     "Roanoke",
                     "Staunton",
                     "Suffolk",
                     "Virginia Beach",
                     "Waynesboro",
                     "Williamsburg",
                     "Winchester",
                     "Washington",
                     "Aberdeen",
                     "Anacortes",
                     "Auburn",
                     "Bellevue",
                     "Bellingham",
                     "Bremerton",
                     "Centralia",
                     "Coulee Dam",
                     "Coupeville",
                     "Ellensburg",
                     "Ephrata",
                     "Everett",
                     "Hoquiam",
                     "Kelso",
                     "Kennewick",
                     "Longview",
                     "Moses Lake",
                     "Oak Harbor",
                     "Olympia",
                     "Pasco",
                     "Point Roberts",
                     "Port Angeles",
                     "Pullman",
                     "Puyallup",
                     "Redmond",
                     "Renton",
                     "Richland",
                     "Seattle",
                     "Spokane",
                     "Tacoma",
                     "Vancouver",
                     "Walla Walla",
                     "Wenatchee",
                     "Yakima",
                     "West Virginia",
                     "Bath",
                     "Beckley",
                     "Bluefield",
                     "Buckhannon",
                     "Charles Town",
                     "Charleston",
                     "Clarksburg",
                     "Elkins",
                     "Fairmont",
                     "Grafton",
                     "Harpers Ferry",
                     "Hillsboro",
                     "Hinton",
                     "Huntington",
                     "Keyser",
                     "Lewisburg",
                     "Logan",
                     "Martinsburg",
                     "Morgantown",
                     "Moundsville",
                     "New Martinsville",
                     "Parkersburg",
                     "Philippi",
                     "Point Pleasant",
                     "Princeton",
                     "Romney",
                     "Shepherdstown",
                     "South Charleston",
                     "Summersville",
                     "Weirton",
                     "Welch",
                     "Wellsburg",
                     "Weston",
                     "Wheeling",
                     "White Sulphur Springs",
                     "Williamson",
                     "Wisconsin",
                     "Appleton",
                     "Ashland",
                     "Baraboo",
                     "Belmont",
                     "Beloit",
                     "Eau Claire",
                     "Fond du Lac",
                     "Green Bay",
                     "Hayward",
                     "Janesville",
                     "Kenosha",
                     "La Crosse",
                     "Lake Geneva",
                     "Madison",
                     "Manitowoc",
                     "Marinette",
                     "Menasha",
                     "Milwaukee",
                     "Neenah",
                     "New Glarus",
                     "Oconto",
                     "Oshkosh",
                     "Peshtigo",
                     "Portage",
                     "Prairie du Chien",
                     "Racine",
                     "Rhinelander",
                     "Ripon",
                     "Sheboygan",
                     "Spring Green",
                     "Stevens Point",
                     "Sturgeon Bay",
                     "Superior",
                     "Waukesha",
                     "Wausau",
                     "Wauwatosa",
                     "West Allis",
                     "West Bend",
                     "Wisconsin Dells",
                     "Wyoming",
                     "Buffalo",
                     "Casper",
                     "Cheyenne",
                     "Cody",
                     "Douglas",
                     "Evanston",
                     "Gillette",
                     "Green River",
                     "Jackson",
                     "Lander",
                     "Laramie",
                     "Newcastle",
                     "Powell",
                     "Rawlins",
                     "Riverton",
                     "Rock Springs",
                     "Sheridan",
                     "Ten Sleep",
                     "Thermopolis",
                     "Torrington",
                     "Worland"]
